version: '3'
services:
    markov-note:
        restart: always
        container_name: markov-note
        build: .
        image: yude/markov-note:latest
        volumes:
          - "./data:/app/data"
        environment:
          # Misskey instance
          - INSTANCE=
          # Misskey API token
          - TOKEN=
          # Length of sentence
          - N=1